services:
  php-fpm:
    build:
      context: ../../
      dockerfile: docker/wordpress/Dockerfile.php-fpm
    volumes:
      - /home/debian/wordpress:/var/www/html:ro
    expose:
      - "9000"

  nginx:
    image: nginx:1.25
    depends_on:
      - php-fpm
    ports:
      - "8080:80"
    volumes:
      - /home/debian/wordpress:/var/www/html:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
